apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: control-plane
  namespace: istio-system
spec:
  # A complete example of maistra.io/v2 ServiceMeshControlPlane can be found at:
  # https://github.com/maistra/istio-operator/blob/maistra-2.0/pkg/apis/maistra/v2/smcp_new.yaml
  proxy:
    networking:
      trafficControl:
        inbound: {}
        outbound:
          policy: ALLOW_ANY
  gateways:
    ingress:
      runtime:
        deployment:
          autoScaling:
            enabled: false
      service: {}
    egress:
      runtime:
        deployment:
          autoScaling:
            enabled: false
      service: {}
    openshiftRoute:
      enabled: true
  policy:
    type: Istiod
  telemetry:
    type: Istiod
  tracing:
    type: Jaeger
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
        ingress: {}
    kiali:
      enabled: true
      install:
        dashboard:
          viewOnly: false
        service:
          ingress:
            enabled: true
  security:
    dataPlane:
      mtls: true
  runtime:
    components:
      pilot:
        deployment:
          autoScaling:
            enabled: false
  profiles:
  - default
