apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: control-plane
  namespace: istio-system
spec:
  proxy:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 128Mi
  gateways:
    ingress:
      runtime:
        deployment:
          autoScaling:
            enabled: true
            minReplicas: 1
            maxReplicas: 5
    egress:
      runtime:
        deployment:
          autoScaling:
            enabled: true
            minReplicas: 1
            maxReplicas: 5
  addons:
    grafana:
      install:
        persistence:
          enabled: true
          accessMode: ReadWriteOnce
    jaeger:
      install:
        storage:
          type: Elasticsearch
          elasticsearch:
            nodeCount: 3
            storage: {}
            redundancyPolicy: SingleRedundancy
            indexCleaner: {}
            resources:
              requests:
                cpu: "1"
                memory: "16Gi"
              limits:
                cpu: "1"
                memory: "16Gi"
  runtime:
    components:
      pilot:
        deployment:
          autoScaling:
            enabled: true
            minReplicas: 1
            maxReplicas: 5
